# -*- coding: utf-8 -*-
"""CV LAB 4

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHMYoGJ5ktxjbtNzNOCEEmrkLPbHcrsO
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt
#Function to display images
def show_comparison(original,sobel,prewitt,canny):
  plt.figure(figsize=(12,10))
  #original Image
  plt.subplot(2,2,1)
  plt.imshow(original,cmap='gray')
  plt.title("Original Gray Image")
  plt.axis('off')
  #Sobel Edge Detection
  plt.subplot(2,2,2)
  plt.imshow(sobel,cmap='gray')
  plt.title("Sobel Edge Detection")
  plt.axis('off')
  #Prewitt Edge Detection
  plt.subplot(2,2,3)
  plt.imshow(prewitt,cmap='gray')
  plt.title("Prewitt Edge Detection")
  plt.axis('off')
  #Canny Edge Detection
  plt.subplot(2,2,4)
  plt.imshow(canny,cmap='gray')
  plt.title("Canny Edge Detection")
  plt.axis('off')
  plt.tight_layout()
  plt.show()
#1.Read an image
img=cv2.imread('/content/images.jpg',0)
if img is None:
  print("Error loading image")
else:
  # ---Sobel Operator ---
  # Gradient in x and y direction
  sobelx=cv2.Sobel(img,cv2.CV_64F,1,0,ksize=3)
  sobely=cv2.Sobel(img,cv2.CV_64F,0,1,ksize=3)
  # Combine gradients
  sobel_combined=cv2.magnitude(sobelx,sobely)
  # --- Prewitt Operator ---
  # Define kernels(Px,Py)
  kernelx=np.array([[1,1,1],[0,0,0],[-1,-1,-1]])
  kernely=np.array([[-1,0,1],[-1,0,1],[-1,0,1]])
  #Apply kernels using filter2D
  prewittx=cv2.filter2D(img,-1,kernelx)
  prewitty=cv2.filter2D(img,-1,kernely)
  prewitt_combined=prewittx+prewitty
  # --- Canny Edge Detection ---
  # Arguments:Image,Thershold1,Thershold2
  canny_edges=cv2.Canny(img,100,200)
  #Display images
  show_comparison(img,np.uint8(np.absolute(sobel_combined)),prewitt_combined,canny_edges)

